name: 'Test Gradle Action'
description: 'Test something'
inputs:
  args:  # id of input
    description: 'arguments of app'
    required: true
    default: 'no arguments'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.task_output }}
runs:
  using: "composite"
  steps:
    - run: |
      set -x
      CHANGED_FILES=`${{ github.action_path }}/changed_files.sh`
      echo "::set-output name=files::$CHANGED_FILES"
    shell: bash
