
name: "Changed files detection"
description: "Find the added and modified files due to a github event"
outputs:
  files:
    description: "Paths of all added or modified files"
    value: ${{ steps.changed-files.outputs.files }}
runs:
  using: "composite"
  steps:
    - name: "Get added and modified files"
      shell: bash
      id: changed-files
      run: |
        set -x
        ${{ github.action_path }}/changed_files.sh
