
name: "Changed files detection"
description: "Find the added and modified files due to a github event"
outputs:
  files:
    description: "Paths of all added or modified files"
    value: ${{ steps.changed-files.outputs.files }}
runs:
  using: "composite"
  steps:
    - name: "Get added and modified files"
      shell: bash
      id: changed-files
      run: |
        set -x
        ${{ github.action_path }}/changed_files.sh
        # COMPARE=$(jq '.compare' $GITHUB_EVENT_PATH)
        # COMPARE_API=$(echo $COMPARE | sed 's/github.com\//api.github.com\/repos\//g'| sed 's/"//g')
        # COMPARE_RESPONSE=$(curl -H "Accept: application/vnd.github.v3+json" $COMPARE_API)
        # CHANGED_FILES=$(echo $COMPARE_RESPONSE | jq -r '.files | .[] | select(.status != "removed") | .filename')
        # echo "::set-output name=files::$CHANGED_FILES"

