on:
  push: 
    branches: "release/v*"

jobs:
  create-dist:
    name: "Create Dist"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: eskatos/gradle-command-action@v1
        with: 
          build-root-directory: app
          wrapper-directory: app
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: installDist
      - name: Deploy dist
        run: ./release.sh
        shell: bash
