on:
  push: 
    branches: "release/v*"

jobs:
  create-dist:
    name: "Create Dist"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Release
        run: ./release.sh
        shell: bash
